### ISSUE TITLE
Audit One-To-Many Bidirectional Associations

### ISSUE THREAD

**Issue by bendavies** [DATA-DOG/DataDogAuditBundle#12]
Hi!

I'm looking to use this bundle, but found OneToMany associations are not recorded on inversed side (mappedBy) of a bi-directional relation.

This makes it hard to see what relations an entity had on creation.
You can see it from owning side, but this isn't really enough for a good audit.

For example If you have  Project with OneToMany Tickets, Ticket->Project is recorded when viewing the diff for a ticket, but Project->Tickets is not recorded when viewing the Project, and it's very hard to find the tickets for a project.

I've had a quick look at the code. We could approach it two ways.
1. use your `AuditSubscriber::associate` method for One-To-Many relations (at the moment it only does Many-To-Many collection changes).
2. Record the collection in the diff, so on the entity diff page you would see a link to all Tickets for a Project (just like on the Ticket diff page you see a single link to a project).

Possible option 1 might be nicer, as `dissociate` could also be used to record removals, for example if a Ticket was deleted, a Project would be `dissociated` from the ticket.

Would you be willing to accept a PR?
Do you have a preference on approach?

Thanks.

**Comment by l3pp4rd** [comment]
Hi, one-to-many is many-to-one from another side which we track. You can fully restore one-to-many collections based on this data.
We cannot store all collection as a changeset, because it might be huge like million of records. I personally do not have one-to-many mappings at all, because it usually is cumbersome and too costly to manage.

From the audit log it is now, you can fully restore the database at any point in time. One-to-any will not be supported in any other way. If you want to display one-to-many collections in the admin page, you can fetch the collection changes from the audit log, sum it and you will have the exact version it was before.

What you are asking, cannot be implemented in sane way. Threat audit log as change history, build whatever you want from it - you have all the options at your fingertips.

**Comment by bendavies** [comment]
Thanks, I understand what you are saying but I'm not sure I can get the data i want from this bundle at the moment.
Consider this example:

On Money, project is created with 3 tickets:
Project 1:
 - Ticket 1
 - Ticket 2
 - Ticket 3

On Tuesday,
Ticket 2 is deleted.

I want to know what Project 1 looked like on Monday. That doesn't looks possible because "Project 1" is stored inside the json diff of the Tickets, and that is not queryable.

Any ideas?

**Comment by l3pp4rd** [comment]
you can query all collection related changes for that project up until monday and build their snapshot at that time. this is not a straight forward task, but one-to-many collections are also complex for that reason. 

you can always fork this bundle and adapt it the way you like for your use cases. I made it generic for reasons mentioned above.

**Comment by bendavies** [comment]
what you're saying is correct, but will be highly impractical for a system of any significant size.

Thanks for the replies!

**Comment by l3pp4rd** [comment]
cheers, we have to make these trade offs in order to prevent more issues, which are much harder to resolve. If I would accept such a change, there would be issues which the library will not be able to fix. So leaving you with a fork if that is more convenient
