### ISSUE TITLE
Unautided fields in audited entity

### ISSUE THREAD

**Issue by krzysztofruszczynski** [DATA-DOG/DataDogAuditBundle#25]
Hello,
  I think about possibility not to log specified fields on audited entity. We could use for each variable representing column (in Entity) such annotation: @DataDogAudit\Unaudited . These information can be used to filter $uow->getEntityChangeSet output (unset unaudited elements in array). Due to that change, we can for example avoid logging critical private data or columns changed automatically by application. If I would develop this functionality, would it be included in audit bundle? (changes in AuditSubscriber, probably new file in DBAL folder) .

**Comment by chancegarcia** [comment]
We use this bundle and have some encrypted columns that could use this.

Bonus if xml config in addition to annotation.

**Comment by l3pp4rd** [comment]
well, everyone seems to misunderstand the purpose of this bundle. it is not for logging just something, it is for Auditing. That means, in general the purpose of this bundle is to audit everything to track what has changed, by whom and in order to be able to fully restore everything based on this log. If you ignore few fields or entities, it looses the whole purpose.

If you store sensitive data without encryption, it is the same security issue as you store it not in the audit log but your standard database table. So what is the difference? This audit bundle has only a single subscriber class in it, you may just copy and adapt it the way you like for your own uses.
Instead of trying to adapt the open source project to your specific use cases.

I understand there are tables which are logs itself or just views of something, these could be skipped from audit. but separate fields is something different here and instead of audit bundle it will become logging bundle. Audit bundle is meant to track the history of any change in database and navigate it if needed, that is the only purpose of it. It does one thing well. I do not want this to become a spaceship of whatever possible use case there is, including logging just few fields in whole database.

Just copy this one subscriber class and adapt it for your own purposes. I do not want later people asking me why, I cannot find a relation if I have a foreignkey column ignored in configuration.

**Comment by krzysztofruszczynski** [comment]
Hi @l3pp4rd  ,
	I see your point. When I talked about critical private data, I thought about things like address (sometimes audit data can be processed by people, who should not see all data).
	I thought about adapting it to my needs, but most of methods are private instead of protected, so you can't just extend class. Is there any reason behind this?

**Comment by l3pp4rd** [comment]
well, the code will not change it does everything properly. so instead of extending this class you just copy it into your source code, inject as a subscriber to ORM event listener and adapt it the way you prefer. It is just that mindset in PHP is like for everything use a dependency no matter how simple the task is. in this case copying a class. If that sounds too complicated, I can accept a pull request with a change to protected methods ;)

**Comment by chancegarcia** [comment]
*facepalm*

I should never write responses before coffee. I already encrypt those columns so the diff would never have sensitive data when recording the audit because reasons. *goes to get more coffee to use words*
